// Defines the AsActionApp class.
// $Author: Paul Ellis.

#ifndef ASACTIONAPP_H
#define ASACTIONAPP_H

#include "asaction.h"

class AsFactory;
class AsUser;

/**
 * Represents an App action object in a flipchart
 */
class AsActionApp : public AsAction
{




public:
    enum AsEnumProperty
    {
        // From AsObject...
        AS_PROPERTY_DATETIMECREATED = 1,

        // From AsActionApp...
		AS_PROPERTY_ACTIONAPPTYPE,
        AS_PROPERTY_CLOCKCOUNT,

		// From AsAction...
		AS_PROPERTY_ACTIONFEATURETYPE,
    };

	enum AsEnumAppActionType
	{
		AS_APPACTION_NONE = 0,
		AS_APPACTION_QUIT,
		AS_APPACTION_OPEN_MY_FLIP_DLG,
		AS_APPACTION_OPEN_SHARED_FLIP_DLG,
		AS_APPACTION_OPEN_OTHER_FLIP_DLG,
		AS_APPACTION_SAVE_MY_FLIP_DLG,
		AS_APPACTION_SAVE_SHARED_FLIP_DLG,
		AS_APPACTION_SAVE_OTHER_FLIP_DLG,
        AS_APPACTION_ABOUT_DLG,
        AS_APPACTION_SHOWPAGENOTES,
        AS_APPACTION_RESETPAGE,
        AS_APPACTION_UNDO,
        AS_APPACTION_REDO,
        AS_APPACTION_SHOWREVEALER,
		AS_APPACTION_CLEARANNOTATIONS,
		AS_APPACTION_CLEARBACKGROUND,
		AS_APPACTION_CLEARGRID,
		AS_APPACTION_CLEAROBJECTS,
		AS_APPACTION_CLEARPAGE,
		AS_APPACTION_GROUP,
		AS_APPACTION_UNGROUP,
        AS_APPACTION_PASTE,
        AS_APPACTION_RECTCAMERA,
        AS_APPACTION_ANALOGCLOCK,
        AS_APPACTION_DIGITALCLOCK,
        AS_APPACTION_ANADIGICLOCK,
        AS_APPACTION_COUNTDOWNCLOCK,
        AS_APPACTION_COUNTUPCLOCK,
        AS_APPACTION_SHOWHELP,
        AS_APPACTION_PRINTDLG,
        AS_APPACTION_QUESTIONEDITOR,
        AS_APPACTION_TOGGLERULER_DEFAULT,
        AS_APPACTION_TOGGLEPROTRACTOR_HALF,
        AS_APPACTION_TOGGLEPROTRACTOR_FULL,
        AS_APPACTION_TOGGLECOMPASS,
		AS_APPACTION_1024X768FLIPCHART,
		AS_APPACTION_800X600FLIPCHART,
		AS_APPACTION_CUSTOMSIZEFLIPCHART,
		AS_APPACTION_SCREENSIZEFLIPCHART,
		AS_APPACTION_ACTIONSBROWSER,
		AS_APPACTION_CALCULATOR,
		AS_APPACTION_SPOTLIGHT_CIRCULAR,
		AS_APPACTION_SPOTLIGHT_INVERSECIRCULAR,
		AS_APPACTION_SPOTLIGHT_INVERSERECTANGULAR,
		AS_APPACTION_SPOTLIGHT_RECTANGULAR,
		AS_APPACTION_CLOSEFLIPCHART,
		AS_APPACTION_DEVICEREGISTRATION,
		AS_APPACTION_DICEROLLER,
		AS_APPACTION_DUALMODE,
		AS_APPACTION_EDITPROFILE,
		AS_APPACTION_EXPRESSPOLL,
		AS_APPACTION_EXPRESSION_QUESTIONWIZARD,
		AS_APPACTION_FLIPCHARTSPELLCHECKER,
		AS_APPACTION_FRACTIONCREATOR,
		AS_APPACTION_CAMERA_FREEHAND,
		AS_APPACTION_CAMERA_POINT2POINT,
		AS_APPACTION_CAMERA_WINDOW,		
		AS_APPACTION_FULLSCREENPHOTO_TOCLIPBOARD,
		AS_APPACTION_FULLSCREENPHOTO_TOCURRENTPAGE,
		AS_APPACTION_FULLSCREENPHOTO_TOMYRESOURCELIBRARY,
		AS_APPACTION_FULLSCREENPHOTO_TOSHAREDRESOURCELIBRARY,
		AS_APPACTION_FULLSCREENPHOTO_TONEWPAGE,
		AS_APPACTION_FULLSCREENPHOTO,		
		AS_APPACTION_GRIDDESIGNER,
		AS_APPACTION_HIDEGRID,
		AS_APPACTION_NEWFLIPCHART,
		AS_APPACTION_OBJECTBROWSER,
		AS_APPACTION_OBJECTSTOFRONT,
		AS_APPACTION_KEYBOARD,
		AS_APPACTION_PAGEBROWSER,
		AS_APPACTION_IMPORTPPT_ASIMAGES,
		AS_APPACTION_IMPORTPPT_ASOBJECTS,
		AS_APPACTION_PROPERTIESBROWSER,
		AS_APPACTION_RESOURCEBROWSER,
		AS_APPACTION_FULLSCREENRECORDER,
		AS_APPACTION_SETROTATIONCENTER,
		AS_APPACTION_SNAPTOGRID,
		AS_APPACTION_SOUNDRECORDER,
		AS_APPACTION_TEACHERLOCK,
		AS_APPACTION_TICKERTAPE,
		AS_APPACTION_TIMESTAMP,
		AS_APPACTION_TOOLBOXROLLUP,
		AS_APPACTION_VOTINGBROWSER,
		AS_APPACTION_WEBBROWSER,
		AS_APPACTION_NEWPAGE_AFTERCURRENT,
		AS_APPACTION_NEWPAGE_BEFORECURRENT,
		AS_APPACTION_SETPAGEBACKGROUND,
		AS_APPACTION_EXTRACTTEXT,
		AS_APPACTION_INSERTLINKTOFILE,
		AS_APPACTION_INSERTLINKTOWEBSITE,
		AS_APPACTION_INSERTMEDIAFROMFILE,
		AS_APPACTION_STARTSTOPVOTE,
		AS_APPACTION_SELECTALL,
		AS_APPACTION_DUPLICATEPAGEBEFORE,
		AS_APPACTION_DUPLICATEPAGEAFTER,
		AS_APPACTION_DUPLICATEPAGEATEND,
		AS_APPACTION_QUESTIONMASTER,
		AS_APPLICATION_OSWEBBROWSER,
		AS_APPACTION_TOOLBOXROLLIN,
		AS_APPACTION_COLOURPICKER,
		AS_APPACTION_SEARCHPLANET,
		AS_APPACTION_PAUSEVOTE,
		AS_APPACTION_EXPORTTESTTOEXCEL,
		AS_APPACTION_SHOWDASHBOARD,
		AS_APPACTION_EDITSTUDENTDATABASE,
		AS_APPACTION_NEWBROWSERWINDOW,
   		AS_APPACTION_1152X864FLIPCHART,
		AS_APPACTION_1280X1024FLIPCHART,
		AS_APPACTION_SOUNDCONTROLLER,
		AS_APPACTION_CUTPAGE,
		AS_APPACTION_COPYPAGE,
		AS_APPACTION_DELETEPAGE,
		AS_APPACTION_TOGGLEDESIGNMODE,
		AS_APPACTION_ASSIGNSTUDENTSTODEVICES,
		AS_APPACTION_INSERTASYNCTEST,
		AS_APPACTION_AREASCREENRECORDER,
        AS_APPACTION_SHOWPENMODIFIER,
        AS_APPACTION_PENMODIFIER_LINE,
        AS_APPACTION_PENMODIFIER_HORIZONTAL_LINE,
        AS_APPACTION_PENMODIFIER_VERTICAL_LINE,
        AS_APPACTION_PENMODIFIER_SQUARE,
        AS_APPACTION_PENMODIFIER_RECTANGLE,
        AS_APPACTION_PENMODIFIER_CIRCLE,
        AS_APPACTION_PENMODIFIER_ELLIPSE,
        AS_APPACTION_PENMODIFIER_CURVE,
        AS_APPACTION_PENMODIFIER_SEMICIRCLE,
        AS_APPACTION_PENMODIFIER_CALLOUT1,
        AS_APPACTION_PENMODIFIER_CALLOUT2,
        AS_APPACTION_PENMODIFIER_ARROWLINE,
        AS_APPACTION_PENMODIFIER_LINE_CHAIN,
        AS_APPACTION_TOGGLERULER_MM,
        AS_APPACTION_TOGGLERULER_CM,
        AS_APPACTION_TOGGLERULER_INCH,
        AS_APPACTION_TOGGLEPROTRACTOR_DEFAULT,
		AS_APPACTION_TOGGLE_SET_SQUARE,
        AS_APPACTION_ACTIVPROGRESS,
        AS_APPACTION_ACTIVIEW,
        AS_APPACTION_SEND_VIA_EMAIL,
        AS_APPACTION_EDITLRSGROUPS,
	};

    // Construction and destruction
    AsActionApp( AsFactory * );
    virtual ~AsActionApp();

    AsActionApp( const AsActionApp& );
    void operator= ( const AsActionApp& );

    void asRun( AsUser*, QPointF );

    // Properties.

    void asResetPropertyIndex();

	void asSetActionType(AsEnumAppActionType actionType);
        AsEnumAppActionType asGetActionType() const;

    void asSetClockCount(int nClockCount);
    int asGetClockCount() const;

    QString typeName() override;

private:
    void asCopy( const AsActionApp& );

    void asSelectPenModifierAction( AsUser*, int index );

    static QHash<QString, quint16>& m_lProperties( void );

	AsEnumAppActionType m_actionType;
    int m_nClockCount;


    void asDoRun( AsUser*, QPointF );


	void asLaunchQuit();
	void asLaunchCloseFlipchart();
	void asAsyncRun(  AsUser*, QPointF );
};

#endif // ASACTIONAPP_H
